-- =============================================================================
-- Phase 4e6: shared.coach_advice - cached per-domain "Coach says" output.
--
-- The inline coach cards on /lifting, /running, /health, /goals each
-- render a short advice string generated by the user's configured LLM.
-- We cache one entry per (user, domain, day) so the model is only
-- invoked once per day per domain - page renders read from cache.
-- Re-generating today just upserts on the unique constraint.
-- =============================================================================

CREATE TABLE shared.coach_advice (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  domain              text NOT NULL
                        CHECK (domain IN ('lifting', 'running', 'health', 'goals')),
  generated_for_date  date NOT NULL,

  advice              text NOT NULL,
  -- Snapshot of the data the model saw; useful for debugging "why did
  -- the coach say X" and for future audit/eval pipelines.
  context_snapshot    jsonb,

  created_at          timestamptz NOT NULL DEFAULT now(),

  -- One advice row per user+domain+day; UPSERT keys on this.
  UNIQUE (user_id, domain, generated_for_date)
);

CREATE INDEX coach_advice_user_recent_idx
  ON shared.coach_advice (user_id, generated_for_date DESC);

ALTER TABLE shared.coach_advice ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users access own coach advice"
  ON shared.coach_advice FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON shared.coach_advice TO authenticated;
